### ISSUE TITLE
Creating new Card via code not working (Card is not a contructor)

### ISSUE THREAD

**Issue by NickIliev** [triniwiz/nativescript-stripe#1]
Using this snippet in TypeScript/JavaScript application
```
import { Card } from 'nativescript-stripe';
const cc = new Card("1111111111111111",2,18,"123");
```
is throwing with
```
nativescript_stripe_1.Card is not a contructor.  ....
... at main-page.js line 6
```

The build is complaining that there are no exported member **Card** and **Stripe** in **_natiescript-stripe/index_** 

How to reproduce: use the demo application to reproduce in Android. (tns-core-modules 2.5.2 and nativescript-stripe 1.0.0)
Also at this stage, the demo application is not loading the Credit Card UI elements at all.
For example the ones [here](https://github.com/triniwiz/nativescript-stripe/blob/master/demo/app/main-page.xml#L8-L10)

**Comment by triniwiz** [comment]
Ok will look into this 😃

**Comment by triniwiz** [comment]
@NickIliev everything should be a ok now 👍
