### ISSUE TITLE
createSource support

### ISSUE THREAD

**Issue by MohammedBashiru** [triniwiz/nativescript-stripe#105]
### Which platform(s) does your issue occur on?
- iOS/Android/Both 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.2.0
- Cross-platform modules: 6.2.3
- Runtime(s): "platforms": {
      "android": "6.0.0",
      "ios": "6.0.1"
    }
- Plugin(s): 6.3.2

### Please, tell us how to recreate the issue in as much detail as possible. 
We need support for creating Sources
Reference from SDK https://stripe.com/docs/mobile/ios/sources

**Comment by RobertGardner** [comment]
What are you trying to do? According to the Stripe documentation, you use Payment Intents on the mobile app to create payment sources. See [Accept a payment](https://stripe.com/docs/payments/accept-a-payment#ios). This interaction is supported by NS-Stripe. (See also, [Transitioning to the Payment Methods API](https://stripe.com/docs/payments/payment-methods/transitioning), which says "The Payment Methods API replaces the existing Tokens and Sources APIs as the recommended way for integrations to collect and store payment information.")

Also, the Stripe iOS sample illustrating the Basic Integration does not use `STPSource` directly.

If you could provide more details about what you are trying to do, I may be able to help.

**Comment by MohammedBashiru** [comment]
thank you @RobertGardner.

Our web app uses the stripe.js to create source,
which then the source id is sent to the backed to create a source object for the customer.

I did not find similar API in the `nativescript-stripe` plugin. Similar was to create payment Token but our API is only implemented for stripe source.

sure the Payment Methods API is the recommended but our back-end API is already implemented with the Sources API.

I have already submitted PR for the source implemented if that's OK by you.

**Comment by RobertGardner** [comment]
Thanks for doing this. I have some comments on the PR.

**Comment by MohammedBashiru** [comment]
@RobertGardner can I get your lint and any other setup so that I don't have to miss any errors when making changes.

if you don't like to share here please email me.
mohammedbashiru63@gmail.com

thanks

**Comment by RobertGardner** [comment]
Yes, no problem sharing it publicly. The lint rules are in the repository, at the root, as `tslint.json`.

The lint rules don't include everything I commented on. Some of those come from the formatter I use. I code with VS Code and use the standard TypeScript formatter with no changes (except preferring double quotes for historical reasons -- I may change that some day since the repository is somewhat inconsistent). These won't cause build failures, but I'd prefer they be used on all code submitted to the repository for consistency.

I also have VS Code set up to highlights all lint errors while I'm editing, so they're easy to catch.

**Comment by MohammedBashiru** [comment]
Seems we have similar setup, 
yet I couldn't catch those petty errors.

The comments were very helpful and 
I wish i can get a setup like that for my other projects.

**Comment by RobertGardner** [comment]
Added in v6.4.0 for credit cards.
