### ISSUE TITLE
com.stripe.android.Stripe is not a constructor

### ISSUE THREAD

**Issue by labidiaymen** [triniwiz/nativescript-stripe#11]
JS: ERROR Error: Uncaught (in promise): TypeError: com.stripe.android.Stripe is not a constructor
JS: TypeError: com.stripe.android.Stripe is not a constructor

Even i have an errror when i am trying to sho the CardView
Need more documentaion, especially on Angular
Thanks

**Comment by labidiaymen** [comment]
![image](https://user-images.githubusercontent.com/3775924/34467214-046adbf6-eeeb-11e7-95fc-456ee48cb1ef.png)

**Comment by triniwiz** [comment]
Fixed https://github.com/triniwiz/nativescript-stripe/commit/4ec277a54a5e18c504eae62c24ac605fad5df963
