### ISSUE TITLE
3D authentication Dialog vs Browser open

### ISSUE THREAD

**Issue by standevo** [triniwiz/nativescript-stripe#113]
I notice that some cards on 3D authentication open a Dialog but others a Browser. I suppose this depends of type of callback and is controlled by the native libraries or there is something else? 

It would be more convenient to open all in dialog because if it leave the app on IOS for example on resume it refresh the view components (in my case is calling `loaded` events)

**Comment by RobertGardner** [comment]
As I understand the documentation, whether it opens in a dialog or browser depends on the card issuer. Some issuers require authentication at the bank's site, others let Stripe do it. Either way, it's controlled by the native libraries.
