### ISSUE TITLE
tns-core-module issues with rc (package namespace change)

### ISSUE THREAD

**Issue by lonemanotzi** [triniwiz/nativescript-stripe#124]
As part of the upcoming tns release, tns* packages no longer supported and is advised to use @nativescript/ packages.
Here is the example  of new package recommendations https://nativescript.org/blog/angular-10-support/ and guidance to remove tns-* packages from package.json

If I use latest nsc (aka tns) with this plugin, it throws module not found error for tns-* packages.

Please let me know if/when you are planning to update this plugin to use @nativescript packages. Appreciate this great plugin for stripe integration.

**Comment by lonemanotzi** [comment]
I see @funder7 is actively working on updating this plugin. Closing this now

**Comment by trane77** [comment]
HI @lonemanotzi I did some work but it's not finished yet, anyway I will continue it in the next weeks ;)

Edit: https://github.com/funder7/nativescript-stripe here's my fork, If you want, try to understand why the CreditCardView class is not being exported in a new Nativescript-Angular project, I suspect that it needs a new Class decorator, that the NS team is working on...I tried so many things without success, it just don't work, unfortunately I don't have time to investigate on the reason right now.
If you want just open a new PR, once the issue will be fixed we can ask this plugin author if he wants to include the update in his version. 
Cheers

**Comment by lonemanotzi** [comment]
Thanks Federico, I did take your PR and try to get it working but I too got the same error and didn't get much time to investigate. I hope @nathanwalker will be able to look at this or mention how to fix in his documentation. I will try to get one of the working plugin and see what else we need to do in weekend.

**Comment by trane77** [comment]
Yes that would be the best option for the moment, did you find an updated plugin to use as blueprint? In case you know one which is working I can import the changes and push them on my repository...we can use that until the PR will be accepted! thank you!

**Comment by lonemanotzi** [comment]
This is the one we can use as a blueprint.
https://github.com/NativeScript/nativescript-ui-charts

If you can try model after this and push to the fork, I can follow-up on
any other issues.

**Comment by NathanWalker** [comment]
Thanks @funder7 and @lonemanotzi - we can help update this plugin - we use it in projects ourselves as well 👍  - Most likely can have it updated by early next week but possibly this weekend; just working on wrapping up cli changes today and can move to this.

**Comment by trane77** [comment]
Ok no problem @NathanWalker!

@lonemanotzi [I've found this](https://github.com/NativeScript/NativeScript/blob/feat/monorepo/packages/core/ui/list-view/index.android.ts) by reading another discussion...the treasure hunt goes on! I will give it a try tomorrow ;)

**Comment by NathanWalker** [comment]
Yep! You can use the new `@NativeClass` decorator in plugins by installing @nativescript/webpack ~2.1.0 in your plugin. You can then use [ts-patch](https://www.npmjs.com/package/ts-patch) to allow tsconfig transforms which enables the decorator by applying to tsconfig as follows:
```
"compilerOptions": {
  ...,
  "baseUrl": ".",
  "plugins": [
      { "transform": "@nativescript/webpack/transformers/ns-transform-native-classes", "type": "raw" }
   ]
```
Then just make sure ts-patch is installed when you build/run/clean the plugin, we like to use something like this:
```
"tsc": "tsc",
"build": "npm i && ts-patch install && npm run tsc && npm run build.angular",
"build.angular": "cd ../src-angular && npm run build",
```
The angular build parts are best to split out into it's own source folder since allows you to use `ng-packagr` on just an isolated source folder and then just copy the `dist` it produces back into your `src` plugin folder in an `angular` folder ready to publish. These details are what we will write about in an upcoming blog post.

**Comment by trane77** [comment]
Thank you very much @NathanWalker, good stuff. Will you update the plugin-seed project to include those changes?
BTW I followed your instructions but @NativeClass decorator cannot be find... hints?
