### ISSUE TITLE
Add Nativescript 6.8.0 & Angular 10 support

### ISSUE THREAD

**Issue by trane77** [triniwiz/nativescript-stripe#125]
Recently the {N} team has introduced some very interesting updates in all their packages:  Angular 10 (with Ivy compiler!) is now supported, and Angular 11 support is in the todo list. 
In order to be compatible with this updates, a plugin must be refactored by following some instructions, that will be released soon in a blog post on Nativescript website. 

I was already working on other plugin updates in order to make them compatible with the latest {N} packages, since I was already in the plugin-update thing, and I needed to integrate Stripe payments in a personal project, I tried to update this plugin too. 
Thanks to Nathan Walker for having shared the changes needed to make the plugin compatible with `ngcc`.

Unfortunately I own an Android phone, and so build/test on iOS is not possible for me. Any contribution about this would be highly appreciated (@triniwiz ?)

Since the last release of the plugin, Stripe updated the SDKs:
- iOS: 15 → 19.3
- Android: 8.7 → 15.1
As you can see the numbers increased significantly, I didn't check but probably a lot of new features were introduced. 

I suggest to keep the SDK version as is for the moment, in order to check that this update has not introduced any new problem, then with the help of Chronos, we will think about this too :)  

Just let me complete the last checks, then I'll submit the PR.

Cheers,
Federico

**Comment by triniwiz** [comment]
I think Nathan has code for this will confirm first

**Comment by ChadStrat** [comment]
+1 any progress on this?

**Comment by trane77** [comment]
HI @ChadStrat please check the discussion here #126 .. In the last days the stable version of nativescript has been released, so instead of releasing an update of nativescript-stripe with a release candidate it's better to use that. A user reported problems on iOS, I did some corrections that hopefully fixed that problems. I will try to finish the update this weekend, stay tuned.

**Comment by triniwiz** [comment]
Please update to {N} v7 then you can try https://github.com/triniwiz/nativescript-plugins
