### ISSUE TITLE
can't import library on iOS 14

### ISSUE THREAD

**Issue by mastashake08** [triniwiz/nativescript-stripe#128]
After ns migrate to Nativescript 7 I get the following error
Module not found: Error: Can't resolve 'nativescript-stripe'

I have to import like this import {mapGetters, mapActions, mapState} from 'vuex'
import {Stripe} from '@triniwiz/nativescript-stripe'
When I do this I get the error stripe.createToken does not exist as a fuction

**Comment by triniwiz** [comment]
Did you install the new package from `@triniwiz/nativescript-stripe` ?

Also the method is now `createCardToken`

**Comment by mastashake08** [comment]
I figured that out but when I do the constructor new Stripe(key) it returns an empty object {}
  this.stripe = new Stripe(this.stripeKey)

**Comment by mastashake08** [comment]
<template>
    <Page xmlns:stripe="@triniwiz/nativescript-stripe">
        <ActionBar title="Checkout!"/>
        <scroll-view height="100%">
        <stack-layout>
        <RadDataForm :source="checkout_cart" />

        <creditCardView id="card"></creditCardView>
        <ActivityIndicator :busy="isBusy" color="black" width="100" height="100"></ActivityIndicator>
        <button class="checkout-btn" :text="`Place Order  $${(delivery_price + total).toFixed(2) }`" @tap="createToken" />
        <label text="All delivery orders have a $5.00 delivery fee attached."/>
        </stack-layout>
        </scroll-view>
    </Page>
</template>

The card doesn't show up 
![Screen Shot 2021-03-20 at 6 52 40 PM](https://user-images.githubusercontent.com/1226096/111887738-75955300-89ad-11eb-89e6-44930a717a0d.png)

**Comment by triniwiz** [comment]
You need to register the view

```ts
import Vue from 'nativescript-vue';
import CardView from '@triniwiz/nativescript-stripe/vue';
Vue.use(CardView);
```

**Comment by mastashake08** [comment]
Bro I did that already. It's not working

**Comment by triniwiz** [comment]
Try `CreditCardView`

**Comment by mastashake08** [comment]
That's what I did at first then I tried CardView

**Comment by mastashake08** [comment]
Do you have WhatsApp?
