### ISSUE TITLE
Readonly fields

### ISSUE THREAD

**Issue by jeremypele** [triniwiz/nativescript-stripe#2]
Hi and thanks for your plugin!

I was wondering if there was a reason why the fields `number, ccv, expMonth, expYear` are readonly?
I wanted to use my own form with binding on those fields but cannot do it for the moment.

Cheers

**Comment by triniwiz** [comment]
The set method for each of those fields are now deprecated

[Android]

https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/model/Card.java#L467

https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/model/Card.java#L484

https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/model/Card.java#L501

https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/model/Card.java#L516

But for iOS you can get the native instance and make the changes as you like 
```
import { Card } from 'nativescript-stripe';
let cc = new Card("1111111111111111",2,18,"123");
let card = cc.card;
card.number = "1234567890111213";
```

Or you can simply use the Card class and create a new instance to assign the numbers/dates

**Comment by jeremypele** [comment]
Thanks for your feedback! Really appreciated :)
