### ISSUE TITLE
validate expiration month with value `1`

### ISSUE THREAD

**Issue by edoardocavazza** [triniwiz/nativescript-stripe#3]
I am trying to validate and expiration month field with value `1` but `card.validateExpMonth` returns false.

According to the Stripe [documentation](https://stripe.github.io/stripe-ios/docs/Classes/STPCardValidator.html#/c:objc(cs)STPCardValidator(cm)validationStateForExpirationMonth:) the `0` and `1` values are incomplete values, but I can not insert `01` because the plugin [requires a number](https://github.com/triniwiz/nativescript-stripe/blob/master/src/ios/card.d.ts#L13).

**Comment by triniwiz** [comment]
good catch i'll update that

**Comment by edoardocavazza** [comment]
Hello @triniwiz, there is a regression in v3.2.1 and the plugin does not validate month with value `1` anymore :(
