### ISSUE TITLE
How to make purchase after token received?

### ISSUE THREAD

**Issue by delanick** [triniwiz/nativescript-stripe#42]
Hi there, once I have my token, how do I make a payment for a purchase? I'm using NS Core with JS. Please advise asap.

**Comment by RobertGardner** [comment]
Purchases can only be made on your backend using one of the many Stripe SDKs. See the documentation at stripe.com for more information. 

If you are using CreditCardView to obtain your token you will want to send the token plus any information necessary to complete the purchase to your backend. This would include your customer ID, shipping details, costs, taxes, and so forth. Your backend will store this in its own storage for fulfillment processing and then use it to create a charge on the Stripe service.

If you are using the standard integration, that will take care of collecting shipping and payment information and sending that to your backend. Your backend will still need to store it and send it to Stripe, as described above.

**Comment by delanick** [comment]
@RobertGardner Perfect, thanks so much!

Unfortunately I just checked their website and see they're not available in my country (South Africa). Do you know of another credit card provider I can use with {N} and in South Africa? Or do you know of a workaround I can use for Stripe?

**Comment by RobertGardner** [comment]
The number of plugins for {N} grows over time. I'm not sure what type of payment processing you are looking for, but this page in {N}'s documentation gives an overview. Hopefully there's something there that will meet your needs:
https://www.nativescript.org/blog/5-plugins-to-monetize-your-nativescript-app

**Comment by delanick** [comment]
Thanks a lot @RobertGardner
