### ISSUE TITLE
Fix build breakage by upgrading to latest NS

### ISSUE THREAD

**Issue by RobertGardner** [triniwiz/nativescript-stripe#47]
Travis CI build breaks on demo-angular because NS libraries are out of date.

NS 5.2 removes the ability to use "short imports" when accessing `tns-core-modules`, but the `tns-core-modules` library in pre-5.2 versions requires support for short imports. With Travis CI loading the latest version of NS, this is causing build breakage.

The fix is to upgrade the plug-in libraries to NS 5.2.

**Comment by rynop** [comment]
Just want to confirm that the commits above do not yet fix the build break correct?  I've tried `tns run ios` against the `upgrade-ns-5.2` branch and the plugin fails to build.  If you expect the build to work, let me know and I can share my log.  Thanks for making this plugin...

**Comment by RobertGardner** [comment]
Correct. Last week while working on this I found this bug: https://github.com/NativeScript/nativescript-dev-webpack/issues/625
which suggests you cannot create a plugin that works with NS5 on both CoreNS and Angular. 

The bug now says "ready for test" so hopefully it will be fixed soon. I'm on vacation right now and will look at it again in a week or so when I get back.

**Comment by rynop** [comment]
Hi @RobertGardner you are probably already on top of this, but bug is now fixed by https://github.com/NativeScript/nativescript-dev-webpack/pull/843 and now in `master` and `nativescript-dev-webpack@next`

**Comment by RobertGardner** [comment]
I upgraded to NS 5.3 and in the demo-angular app installed `nativescript-dev-webpack@next`. This fixed the build breakage. Check the latest version of the `upgrade-ns-5.2` branch.

The `demo` and `demo-angular` apps run if I do not bundle them. However, I am unable to run the `demo-angular` app if I use `--bundle` though `demo` runs. I'm still looking into that. There is a chance this is an artifact of how the demo apps are built (using `"nativescript-stripe": "file:../src"`) though it may also be a related webpack bug. The plugin may work in a standard installation (still exploring).

I'll continue my exploration over the next few days.

**Comment by RobertGardner** [comment]
I confirmed that it was just how the `demo-angular` app is configured for development. If I create a publishable version of the plugin and use that instead, then it builds and runs correctly with `--bundle`. So I will create a PR and publish a new version.
