### ISSUE TITLE
Apple Pay not showing under std integration

### ISSUE THREAD

**Issue by rynop** [triniwiz/nativescript-stripe#50]
I'm having trouble getting apple pay to show on the `demo-angular` app, using standard integration, when on the "Select Payment" view.

Followed the stripe [setup steps](https://stripe.com/docs/apple-pay/apps), creating merchant ID, uploading the `.csr` to Stripe, and enabling Apple Pay in xcode.  When I `tns run ios` I see iOS making network calls (presumably negotiating if apple pay is setup), however apple pay option is never displayed when I hit "Select Payment" (add credit card is auto displayed).

Do you have any tips on how to debug? I've verified the [appleMerchantID](https://github.com/triniwiz/nativescript-stripe/blob/master/demo-angular/app/demo/stripe.service.ts#L18) is set correctly in the service.  The `[C*]` iOS network logs are hard to read, however I don't see any errors.

Once I get this working, I'll contribute back to the README.md all the steps I had to do to get the `demo-angular` project to this point (there were a few non-intuitive steps).

thanks in advance.

### Which platform(s) does your issue occur on?
iOS, physical device

### Please, provide the following version numbers that your issue occurs with:

- CLI: `5.3.2`
- Cross-platform modules: `5.3.1`
- Runtime(s): `5.3.1`
- Plugin(s): [demo-angular package.json](https://github.com/triniwiz/nativescript-stripe/blob/master/demo-angular/package.json)

**Comment by RobertGardner** [comment]
The plugin simply turns around and calls the native Stripe iOS library (on GitHub here: https://github.com/stripe/stripe-ios/tree/v13.2.0/Stripe). It is calling STPPaymentContext.presentPaymentMethodsViewController to display the payment selection dialog. Have you tried debugging into the plugin to see if you can find anything there? If you just clone the plugin repository and run in VSCode you should be able to set a breakpoint in the plugin (in the src/ folder). There are npm scripts to help with this (such as `npm run demo-angular.ios` from the src/ directory).

I haven't been able to work through the Stripe SDK code to find where it's deciding if it should display the ApplePay option, but I believe it's based solely on the presence of the appleMerchantID. It may be calling iOS to get more information, such as whether or not ApplePay is enabled on the device. It's possible iOS is making network calls to validate your merchant ID, but I can't say for sure.

I would suggest running in an emulator that is configured for recent hardware, such as iPhoneX, and making sure ApplePay is enabled in the emulator. If that works then it's probably your hardware device. If it doesn't, then there is probably something about your Stripe and/or Apple Merchant ID setup. To check those, I would suggest running Stripe's iOS example (which the plugin is based on -- it's mostly just a port of the Swift example into NativeScript). You can build and run the example in XCode. The example is at https://github.com/stripe/stripe-ios/tree/master/Example/Standard%20Integration%20(Swift)

If everything works in the Stripe Example code but not in an emulator, let me know. 

(Note that the plugin currently works with Stripe 13.2, but the current Stripe iOS library is at 15.0.)

**Comment by rynop** [comment]
Robert, I REALLY appreciate your prompt and thorough responses.  Gone above and beyond here buddy...

`demo-angular` works with apple pay when running on the emulator.  Doesn't show up on my physical device.  Both my device and emu. are iOS 12.2 (iPhone X).  Running `tns run ios --syncAllFiles` with both the emu and phys. device connected, and only emu works.  I've uninstalled the app from phone (hold,wobble,hit x to uninstall), no dice.

I use apple pay all the time from my phone and the stripe [web app demo](https://stripe.com/en-US/apple-pay) works.

I can't get the stripe standard integration example to work. I have bug open (https://github.com/stripe/stripe-ios/issues/1164) against the project.

The only difference I notice between emu/phys is the logging on the HTTPS connection phase.

Emulator TCP log is tidy:
```
Successfully synced application com.rynop.stripe.demoangular on device 60F06CC7-C8FF-4313-8EB5-76E7D1698515.
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:16874:24: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
(libnetwork.dylib) [com.apple.network:] [C1 nativescript-stripe.herokuapp.com:443 tcp, url hash: c4506f75, tls] start
(libnetwork.dylib) [com.apple.network:] [C1 nativescript-stripe.herokuapp.com:443 tcp, url hash: c4506f75, tls] cancel
(libnetwork.dylib) [com.apple.network:] [C1 nativescript-stripe.herokuapp.com:443 tcp, url hash: c4506f75, tls] cancelled
[C1.1 18CBDCFC-906F-45DE-B057-509A54C824BC 192.168.0.26:50366<->3.90.23.170:443]
Connected Path: satisfied (Path is satisfied), interface: en7
Duration: 37.309s, DNS @0.002s took 0.019s, TCP @0.024s took 0.038s, TLS took 0.086s
bytes in/out: 3998/851, packets in/out: 5/4, rtt: 0.036s, retransmitted packets: 0, out-of-order packets: 0
(libnetwork.dylib) [com.apple.network:] 0.000s [C1 84D8480A-3B9E-4CF7-8DA1-1EE237E5C5DF nativescript-stripe.herokuapp.com:443 resolver] path:start
(libnetwork.dylib) [com.apple.network:] 0.000s [C1 84D8480A-3B9E-4CF7-8DA1-1EE237E5C5DF nativescript-stripe.herokuapp.com:443 resolver] path:satisfied
(libnetwork.dylib) [com.apple.network:] 0.002s [C1 84D8480A-3B9E-4CF7-8DA1-1EE237E5C5DF nativescript-stripe.herokuapp.com:443 resolver] resolver:start_dns
(libnetwork.dylib) [com.apple.network:] 0.021s [C1 84D8480A-3B9E-4CF7-8DA1-1EE237E5C5DF nativescript-stripe.herokuapp.com:443 resolver] resolver:receive_dns
(libnetwork.dylib) [com.apple.network:] 0.062s [C1 84D8480A-3B9E-4CF7-8DA1-1EE237E5C5DF nativescript-stripe.herokuapp.com:443 resolver] flow:finish_transport
(libnetwork.dylib) [com.apple.network:] 0.148s [C1 84D8480A-3B9E-4CF7-8DA1-1EE237E5C5DF nativescript-stripe.herokuapp.com:443 resolver] flow:finish_connect
(libnetwork.dylib) [com.apple.network:] 0.149s [C1 84D8480A-3B9E-4CF7-8DA1-1EE237E5C5DF nativescript-stripe.herokuapp.com:443 resolver] flow:changed_viability
```

Physical device is not tidy.  I'm very fluent in HTTP but I can't decipher the iOS logs:

[Gist of log](https://gist.github.com/rynop/94d21e1598478081427c2036d4059a7e)

As for debugging, I have VS code debugger attached, and hit the breakpoint here:
![image](https://user-images.githubusercontent.com/372730/56390152-f4e1e100-61f0-11e9-8382-eb4e45831276.png).  Catch is, I only hit this breakpoint when I tap on `Select Payment`, at this point the handshake with stripe and apple to determine Apple Pay capability has already occurred.  Said another way, on the emulator where apple pay works, on the `Payment type` row (on `Details` page) Apple pay will show up after displaying the spinner for a few secs.  The `Select payment` text does not show, in its place is "apple pay" by default.

So I think the failed "check to see if apple pay is supported on this device" has happened before `presentPaymentMethods()` is called...

Any ideas why it might be working on emulator and not physical device?

**Comment by rynop** [comment]
I got it working, and I can't tell you why lol.

I found this issue https://github.com/tipsi/tipsi-stripe/issues/77 .  I had already done the steps outlined here (enable apple pay in capabilities, and check the merchant id box).

All I did was uninstall the app, open the `demoangular.xcworkspace`, turn off apple pay, turn on apple pay, check the box next to merchantID.  I then ran (pressed play) from XCode.

As with most mysterious problems in Apple land, I blame the overly complex/buggy entitlements architecture.

**Comment by RobertGardner** [comment]
Nice! I just tried running demo-angular on my hardware phone (I'd never done that before, always using the emulator) and Apple Pay doesn't show up. I'll try the steps you give (later, busy right now) and see if it fixes it for me! :-)

Thank you. I won't close the issue until I've got Apple Pay working on my hardware phone.

I look forward to your updates to the README. I knew the documentation was lacking but never took the time to enhance them. Thank you!

**Comment by RobertGardner** [comment]
That procedure worked for me as well. When deploying to Apple App store you also need to make sure the capabilities are set properly in XCode before building your archive. I can't find a way to set that in the app code, so NativeScript overwrites the value every time you delete `platforms/ios` or prepare a release. That is quite a nuisance! Hopefully there is a way to do this and I'm just missing it.

**Comment by RobertGardner** [comment]
Note: I found the plugin `nativescript-custom-entitlements`, which seems to manage the entitlement properly.

**Comment by rynop** [comment]
I'm confident there is a way to get the entitlement/capability for apple pay into `App_Resources/ios` without the need for another plugin.   This entitlement merge capability is built into nativescript.  Ex [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#copy-the-entitlements-file).  

This specific task was on my todo list for today, when updating https://github.com/triniwiz/nativescript-stripe/pull/52 . I'll make sure to include what I find.

**Comment by RobertGardner** [comment]
Thanks, I didn't realize the firebase plugin does that copy. I can use that instead of the `nativescript-custom-entitlements` plugin.

Note, though, that the firebase plugin has a script that does the copying. If you look in its `src/scripts` folder the are `entitlements-[before|after]-prepare` scripts that do the copying with essentially the same code used by the `nativescript-custom-entitlements` plugin.

**Comment by rynop** [comment]
I'm pretty confident https://github.com/Essent/nativescript-custom-entitlements is baked into nativescript cli since v5.1.8. I tested this theory on `demo-angular` by `rm -rf platforms`, creating a `app/App_Resources/iOS/app.entitlements` and re-running `tns run ios`. Verified on emulator and pysical device. 

To summarize, I don't think `demo-angular` has any non core nativescript cli dependencies that would copy `app.entitlements`, so I'm deducing its baked into ng-cli.  @RobertGardner if you could please also test this theory on your setup I'd appreciate the double check.

**Comment by rynop** [comment]
Oh I'm also basing my theory on what Eddy says here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md#copy-the-entitlements-file

> Note that since plugin version 5.1.8 the name of the file can either be <YourAppName>.entitlements or app.entitlements. YourAppName is the iOS foldername, see the path above.

I think he meant ns cli version not "plugin version" here..

**Comment by rynop** [comment]
Sorry for the spam.  I think the proof of the `app.entitlements` feature being baked into nativescript-cli is here: https://github.com/NativeScript/nativescript-cli/pull/2753

@RobertGardner what you think?  Its a bummer this is not documented anywhere in nativescript docs (I spent 5 mins searching)

**Comment by RobertGardner** [comment]
Wow, that PR says it was merged May 18, 2017! I had searched NS docs, StackOverflow, and the NS github repository. Good find! I especially like that you offered to add the documentation to NS docs. (Quick note: I think Eddie did mean the plugin version because if you look in `scripts/` at the entitlements scripts you can see it specifically checking for both `YourAppName` and `app`. When I first started using the firebase plugin it did not have this functionality but was added later.)

The best way to confirm that the entitlements file is being copied is to do what you did (delete `platforms/ios` and rebuild) but then check in `platforms/ios` for a file named `platforms/ios/YourAppName/YourAppName.entitlements`. If it's working correctly, `tns prepare` will create that file and copy the contents of your entitlements file into it.

Thanks for all this research!

**Comment by rynop** [comment]
NP. thank you! Yep I think we can mark the case as closed.  That 2753 PR combined with what I'm seeing proves it.
