### ISSUE TITLE
Cannot find name 'STPPaymentMethod'.

### ISSUE THREAD

**Issue by standevo** [triniwiz/nativescript-stripe#58]
After updating to latest version (5.3.0) I get an error:

```
ERROR in node_modules/nativescript-stripe/index.d.ts(100,29): error TS2304: Cannot find name 'STPPaymentMethod'.
node_modules/nativescript-stripe/index.d.ts(131,29): error TS2304: Cannot find name 'STPPaymentIntent'.
```

**Comment by RobertGardner** [comment]
You need to update your pod file. Run
`pod repo update`
Then if necessary clean your old build by deleting the `platforms` and `node_modules` folders and try again.

**Comment by standevo** [comment]
@RobertGardner Thx for trying to help but on android I don't have any pod
  
on `index.d.ts` `STPPaymentMethod` and `STPPaymentIntent` are not declared interfaces.

It's missing somethink like:

```
export declare interface STPPaymentMethod {}
export declare interface STPPaymentIntent {}
```

**Comment by RobertGardner** [comment]
Oh, that's a bug! There shouldn't be any references to STPxxx in the index.d.ts files. I wonder how that got past our continuous integration build. 

All such references should be replaced with `any`. 

Thanks for catching this. I'll fix that later today and publish an update.

**Comment by standevo** [comment]
Thx. Good luck.

Issue can be closed.
