### ISSUE TITLE
Android createToken only send back tokenId

### ISSUE THREAD

**Issue by SBats** [triniwiz/nativescript-stripe#6]
Hi!
First of all, thanks a lot for this plugin!

I wanted to know if there's a reason why the android version of `createToken` send back the result of `token.getId` instead of the whole token object (like the iOS version do)?
If not I can do a pull request to correct it if you wish, it's a very small change.

Thank you in advance for your time and help!

**Comment by triniwiz** [comment]
Feel free to create a pr :)

**Comment by SBats** [comment]
Fixed and closed by https://github.com/triniwiz/nativescript-stripe/pull/7
