### ISSUE TITLE
Save card for later using standard integration?

### ISSUE THREAD

**Issue by rynop** [triniwiz/nativescript-stripe#60]
Sorry this is not a bug, more of a q on the capability of this plugin.  I'm willing to put the work in to extend if feature DNE.

I'd like [save a card for later](https://stripe.com/docs/saving-cards).  Is it possible to "collect" payment info in a platform independent way, to get the source token, without submitting a payment? 

Was hoping completion of [step3 here](https://stripe.com/docs/mobile/ios/standard#handle-payment-option) (`onPaymentDataChanged()` in this lib I think) would auto-save the card up to the customer obj in stripe (via `StripeCustomerSession`), but it does not.

On iOS I think you can get at it from the [STPPaymentConfiguration](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentConfiguration.html#/c:objc(cs)STPPaymentConfiguration(py)createCardSources), which looks to be accessible from the `STPPaymentContext` object.  This obviously is not platform agnostic way to get at the data though.

Said another way, if the card input is presented via `paymentSession.presentPaymentMethods();` can I get the `source` id hash of the entered card without having to hit the "buy" button.

**Comment by RobertGardner** [comment]
Are you trying to make the card available for the customer to use later without reentering the info? Or are you trying to use it for a later payment, such as for a subscription service?

Saving with the customer for later reuse:
Stripe will do this automatically, but you have to create a separate Stripe Customer for each of your own customers. When you create your own customer, create a new `StripeCustomerSession`. In your backend, if you get a request for an ephemeral key that is not yet associated with a customer, create a new Stripe Customer (using the node API, for example) and store the resulting customer ID into your own customer database. Then pass that customer ID into your `createCustomerKey` backend implementation and use it when looking up the ephemeral key. If you need more information, let me know and I can share snippets of the mobile and backend code that I use to do this.

Use for later payment:
This is more complex. You need to read the Stripe documentation on how to do this, see [Reusable Sources](https://stripe.com/docs/sources/customers#reusable-sources). Most of the work happens in your backend. Again, I can share snippets of the code I use to do this.

**Comment by rynop** [comment]
Appreciate the quick and complete (as always) response.

Anyway I can PM you the answer to your q?  I'm kinda getting into proprietary details, which I'm fine sharing with you just not others.  I know you are not customer support, and I value your time - so I'm more than happy to give you amazon gift card or the like.  I just added you on LinkedIn so I'll PM you there if that is OK?

Feel free to close this issue as it sounds like this lib supports both scenarios.

**Comment by RobertGardner** [comment]
PM would be great. I'll look for the conversation on LinkedIn.

Thanks for the offer of gift cards, but I get plenty of enjoyment just from being able to help others! (I do this on my own in my spare time. In my professional life I work for Google but do so much management now that I don't get much time for code at work. This (and my personal projects) keeps me sane. :-)
