### ISSUE TITLE
Shipping address always required for standard integration

### ISSUE THREAD

**Issue by rynop** [triniwiz/nativescript-stripe#63]
### Which platform(s) does your issue occur on?
- Both iOS/Android
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

I'm using the `demo-angular` source as is, against master (commit https://github.com/triniwiz/nativescript-stripe/commit/a10a299f7f44ccceb2672dc522294543063c95c4)
✔ Component nativescript has 5.3.4 version and is up to date.
✔ Component tns-core-modules has 5.3.2 version and is up to date.
✔ Component tns-android has 5.3.1 version and is up to date.
✔ Component tns-ios has 5.3.1 version and is up to date.

### Please, tell us how to recreate the issue in as much detail as possible. 

For my use case I don't have a product to ship, so do not want to collect shipping info.  There is a bug that breaks the flow when you specify no shipping address collection.

Each of these tests, I start out with a customer who has NO shipping info attached to customer obj in stripe backend.  If customer has CC or shipping info on file, clear them using stripe web admin UI.

1.  comment out `StripeConfig.shared().requiredShippingAddressFields...`)
1.  comment out `this.component.shippingInfo = data.shippingInfo;`

**Bug1: iOS** 
1.  add card, do not enter shipping info, hit buy
1.  following error on iOS (emu and phys):
```
CONSOLE ERROR [native code]: ERROR TypeError: null is not an object (evaluating 'address.name')
```

This is due to a bug where [createAddress() ](https://github.com/triniwiz/nativescript-stripe/blob/master/src/standard/standard.ios.ts#L252)always assumes `address` is set.  Simple fix, PR below.

**Bug2: Android** 
1.  add card, get error in console (after saving card/hitting check):
```
System.err: java.lang.NoSuchFieldException: No field mCollapsingTextHelper in class Landroid/support/design/widget/TextInputLayout; (declaration of 'android.support.design.widget.TextInputLayout' appears in /data/app/com.rynop.stripe.demoangularsdkupdate-mRMdVMcVzwZIvmlrkrTSzA==/base.apk)
```

**Bug3: Android** 
1.  Add card
1.  Do not enter shipping info.  
1.  CANT hit buy (button disabled).

Since `StripeConfig.shared().requiredShippingAddressFields` is not set, `canBuy()` should return `true`.  `this.paymentSession.isPaymentReady` is resolving to false for some reason.  This one is out of my expertise level.  I don't know why on android `this.native.getPaymentSessionData().isPaymentReadyToCharge();` is resolving to `true`.  I need help on this one...

**Comment by RobertGardner** [comment]
Bug 1: PR in progress

Bug 2: Weird. It looks like a bug in the Stripe SDK since the plugin doesn't specifically manipulate any widgets. This will take more investigation.

Bug 3: According to the [Stripe Android SDK code](https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/PaymentSessionData.java), `config.isShippingMethodRequired()` and `config.isShippingInfoRequired()` both need to be set to false. This is done in `standard.android.ts` line 30, but only `isShippingMethodRequired` is being set. Try adding a line to set `isShippingInfoRequired` and see if that fixes it.

**Comment by rynop** [comment]
You were very close, you pointed me in the right direction which allowed me to squash another related bug while in there. pr#65^
