### ISSUE TITLE
Please add support of generating tokens for bank account 

### ISSUE THREAD

**Issue by standevo** [triniwiz/nativescript-stripe#74]
Besides of card tokens I'm looking for generating tokens for bank accounts, would be nice to support also this feature.

**Comment by RobertGardner** [comment]
I don't have time to do this, but I'd be happy to answer questions and review a PR.

It looks like you can easily generate bank account tokens using the Custom Integration methods. For iOS, you want to call `STPAPIClient.createTokenWithBankAccount:completion:` ([doc]( https://stripe.dev/stripe-ios/docs/Classes/STPAPIClient.html#/c:objc(cs)STPAPIClient(im)createTokenWithBankAccount:completion:)). You would probably put this code in `stripe.ios.ts` similar to the existing method `createToken(card, cb)` and following the pattern there.

You will need to write your own UI to collect the user's bank account information and use that to create a `STPBankAccountParams` ([doc](https://stripe.dev/stripe-ios/docs/Classes/STPBankAccountParams.html)).

You'll need to find the equivalent Android methods, then create a device-independent representation, similar to how `Card` is defined.

**Comment by csi-stasik** [comment]
@RobertGardner Thank you for your answer. If I remember correctly for android this method are not available. Anyway as workaround I used directly web API (/v1/tokens)
