### ISSUE TITLE
Stripe SDKs out of date; Upgrade needed for latest SCA process

### ISSUE THREAD

**Issue by ordapad** [triniwiz/nativescript-stripe#78]
Stripe SDKs out of date; Upgrade needed for latest SCA process

### Which platform(s) does your issue occur on?
- Android 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.4
- Cross-platform modules: 4.2.2
- Runtime(s): 5.3.1
- Plugin(s): nativescript-stripe 5.4.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Trying to use stripe.createPaymentMethod and this is failing due to old stripe-android SDK.

`const cardParams = new com.stripe.android.model.PaymentMethodCreateParams.Card.Builder();`

*PaymentMethodCreateParams does not exist* on com.stripe.android.model

### Is there any code involved? 
  nativescript-stripe/src/platforms/android/include.gradle should be upgraded to 9.3.7

**Comment by RobertGardner** [comment]
When `PaymentMethod` was first implemented in the plugin, using Android v8.7.0, `Stripe.createPaymentMethod` could only be called synchronously, and not on the UI thread.

With v9.3.8, Stripe has fixed this, so the method you want could be implemented (call `Stripe.createPaymentMethod` instead of `Stripe.createPaymentMethodSynchronous`).

The Stripe Android team, though, has been very busy and the API differences between v8.7 and v9.3 are substantial. Therefore I won't be able to move to v9.3 for awhile. If you'd like to help, you'll need to create a new `java!Stripe.d.ts` file for v9.3.8 following the instructions in the comments at the top of that file. Then fix all the compilation errors. Finally, change the call to `createPaymentMethod` to use the asynchronous method.

Note that, from the best I can tell, `Stripe.createPaymentMethodSynchronous` works in the current version of the plugin (v5.4.3, which uses Stripe Android v8.7.0) as long as you do not call it on the UI thread. (That is, I couldn't recreate the compilation error you report, but did get an exception that `createPaymentMethod` was called on the UI thread.)

**Comment by jeremypele** [comment]
Hi there, I've started the SDK update for Android (https://github.com/jeremypele/nativescript-stripe/pull/1/files)

It's indeed a huge job and would gladly accept any help on it

**Comment by jeremypele** [comment]
And FYI, even with latest SDK version, call cannot be made on the UI Thread 
cf: https://stripe.com/docs/payments/payment-intents/android#collect-card-info-manual

**Comment by RobertGardner** [comment]
Yes, but there is a non-synchronous version (`createPaymentMethod()`) that I believe can be called on the UI thread.

(In a week or two I should be able to help out with the update.)

**Comment by jeremypele** [comment]
> Yes, but there is a non-synchronous version (`createPaymentMethod()`) that I believe can be called on the UI thread.
> 

Yes you're right, made it work on Android from the main thread

**Comment by jeremypele** [comment]
@RobertGardner I think I've finished the update, I just have an issue on Android with Credit Card being created in the session but not listed in the Customer Source List. Only issue, otherwise full flow and demo updated

**Comment by carlosanjos** [comment]
@jeremypele don't forget to include SetupIntents (https://stripe.com/docs/payments/cards/saving-cards#submit-card-details)

**Comment by jeremypele** [comment]
@carlosanjos Don't forget that I've opened a PR and mentionned it above so anyone can have a look and participate :)

**Comment by carlosanjos** [comment]
Great work 🎉@jeremypele
@RobertGardner You could create a new release and tag it like 6.0.0 and close this issue, please.

**Comment by RobertGardner** [comment]
Sorry, I've been traveling without access to my laptop, so I've been unable to deploy a release. I will do it on Tuesday.

**Comment by ordapad** [comment]
Thanks so much @RobertGardner and @jeremypele for your efforts on this. Looking forward to getting the 6.0.0 release now.

**Comment by sebj54** [comment]
Hi there, what is the status of this feature? It seems done in the 6.0.0 release but I can't find a way to do it from the docs.

Only way to get the code is from the angular example?

**Comment by RobertGardner** [comment]
Yes, it's in there. It's not simple to do and much implementation needs to be done server-side, so we didn't provide extensive documentation. The Angular example provides the most detail. The comments and documentation have links to Stripe, which will also be needed to work through the server-side implementation.

jeremypele did most of the implementation on this and may be able to answer questions.

**Comment by jeremypele** [comment]
@sebj54 @RobertGardner Hey guys, yes indeed you'll find full SCA flows in the angular app.
What are you trying to do that you cannot find?

New Stripe Intents are not too much detailled in the plugin as it's not his role to do so IMO.

The readme provides a short summary of the implementation in the [SCA section](https://github.com/triniwiz/nativescript-stripe#strong-customer-authentication). Would probably worth to improve it if it's not clear enough

**Comment by sebj54** [comment]
Hi guys, thanks for your quick answer!

I'm actually just planning a future development but I'm not sure I will need to use SCA-related functions. My need is to collect credit card information (create a PaymentMethod), link it to an account and charge customers based on the usage of my app. 

I'll check the Angular example when I'll start doing it and let you know if I need some extra details.

**Comment by jeremypele** [comment]
@sebj54 You'll need to read the Stripe card collection documentation but as sources are deprecated I strongly advise you to use `SetupIntents` to save cards on an account. `PaymentMethod` doesn't do much on his own.
And you'll use `PaymentIntents` to charge the customer
