### ISSUE TITLE
Problem in angular type project

### ISSUE THREAD

**Issue by pagyx93** [triniwiz/nativescript-stripe#9]
Hi, I don't understand why I can't use this plugin from view in angular 2 project. I use the <CreditCardView> tag in html, but not working. Thanks

**Comment by triniwiz** [comment]
You need to register the view

**Comment by chrispaulsantos** [comment]
How do you register the view? I've done the xmlns:stripe on my root page, but nothing shows up still

**Comment by lordalex** [comment]
same issue here.

**Comment by triniwiz** [comment]
I forgot to include how to register the view in Angular so you need to do the following 

```ts
import { registerElement } from "nativescript-angular/element-registry";
registerElement("CreditCardView", () => require("nativescript-stripe").CreditCardView);
```
